# Welcome to selvin11!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Selvin Blog
email: 528370630@qq.com
description: "Selvin Blog" # this means to ignore newlines until "baseurl:"
keyword: "前端 博客 分享 小白"
baseurl: "http://selvin11.github.io/selvin.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# twitter_username: codeselvin
github_username:  selvin11
zhihu_username: too-zi
weibo_username: codeselvin
facebook_username: codeselvin
# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "做一个浪漫的程序猿，带上我美丽的小老婆一起飞。"
sidebar-avatar:  'http://selvin11.github.io/selvin.github.io/img/dog.jpg'    # use absolute URL, seeing it's used in both `/` and `/about/`

# Build settings
# 设置不解析的文件类
exclude: ["sass","node_modules","Gruntfile.js","package.json","README.md"]
# 代码高亮设置
highlighter: rouge 
# 默认路径
source:   .
destination: ./_site

# 启用Github扩展的markdown语法
markdown: kramdown
kramdown:
  input: GFM



# 分页
paginate: 5
paginate_path: "page:num"
# 插件管理（paginate显示部分文本内容） This will require each of these gems automatically.
gems: [jekyll-paginate]

# tags
featured-tags: true
featured-condition-size: 1 

# Duoshuo settings
duoshuo_username: codeselvin
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true  

# friends blog
friends: [
    {
        title: "Gsw's Blog",
        href: "http://selvin11.github.io/selvin.github.io/"
    },{
        title: "Jessica",
        href: "#"
    },{
        title: "",
        href: "#"
    },{
        title: "",
        href: "#"
    },{
        title: "",
        href: "#"
    }
]